### ISSUE TITLE
Plugin does not work in UE4 4.24

### ISSUE THREAD

**Issue by alextecplayz** [thomasfn/HL2UE4AssetImporter#1]
It doesn`t work.It says to rebuild the source or something like that.
Do i REALLY need to have 4.22?

**Comment by MrSoup678** [comment]
I played with this on 4.24. I got it to run on Linux. Also Changed how the Libraries are handled.

I'll try with Windows soon enough.

**Comment by MrSoup678** [comment]
Why i changed lib handling? Beacuse the upstream violates UE4 EULA. VTFLib has LGPL license 
(strong, **viral**, copyleft). Which means I can such library link only dynamically. This plugin essentialy links them statically.

**Comment by MrSoup678** [comment]
For this same reason this repo (or any UE4 Project or Plugin for that matter) cannot be licensed under any of the GNU licenses.

**Comment by alextecplayz** [comment]
It doesn`t work for me on 4.24.3 and i`m on Windows.I just don`t know what to do.I`ll try again and post back if it doesn`t,if you can fix (or at least try to fix the issue)

**Comment by alextecplayz** [comment]
Nope,still experiencing the issue
Here it is:
Missing <project name>(AssetImporterSource) Modules
The following modules are missing or built with a different engine version:
HL2Runtime
HL2Editor

Would you like to rebuild them?
Yes / No

After clicking yes and waiting a brief moment this is what i get

Error
<project name>(AssetImporterSource) could not be compiled.Try rebuilding from source manually

AssetImporterSource is the name of my blank project.Is it because i have chosen blueprints instead of c++?
How do i fix this?

**Comment by thomasfn** [comment]
My apologies, I didn't get any notifications about this issue. I'm going to be updating the plugin to 4.25.0 soon.

@SlawekNowy can you detail what exactly you changed to link VTFLib dynamicly?

**Comment by MrSoup678** [comment]
Sure. I built them before I build the Plugins. [This](https://docs.unrealengine.com/en-US/Programming/BuildTools/UnrealBuildTool/ThirdPartyLibraries/index.html) guide was extremely helpful. The source to library itself landed in Source/ThirdParty. One note however. In linux link to Clang's C++ STL rather than gcc's.

**Comment by MrSoup678** [comment]
I'd show my fork but I removed it during the cleanup. I don't have a local copy too.

**Comment by MrSoup678** [comment]
I can however show you an example: [This Ogg module used by UE4](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/ThirdParty/Ogg/UEOgg.Build.cs)

**Comment by thomasfn** [comment]
Nice, I'll have a go at doing that, thanks.

**Comment by thomasfn** [comment]
Plugin has since been updated to support 4.25 (I'm not interested in supporting versions earlier than latest). VTFLib issue moved to #2.
