### ISSUE TITLE
UE4 version

### ISSUE THREAD

**Issue by tmb722** [thomasfn/HL2UE4AssetImporter#9]
I see this was migrated to UE5. Is the UE4 version available? I'm using 4.27 and would like to install and test this plugin. Thanks.

**Comment by OneVoltTen** [comment]
I'm not the developer, but this still builds in UE4.27.2

**Comment by tmb722** [comment]
> I'm not the developer, but this still builds in UE4.27.2

I didn't find this to be the case at all. I tried the current version of the plugin, as well as some of the previous versions going back through the change logs. Nothing so far will compile with 4.27.

**Comment by thomasfn** [comment]
The last supported UE4 version was UE4.25 off the top of my head, as the gap between 4.25 and 5.0 was when I wasn't working on the project. I won't be going back and supporting UE4 anymore I'm afraid as it would take too much time. I will try and make a better effort of adding tags to commits in the future when moving between engine versions though.
